//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReadingEvent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }

        [Required (ErrorMessage ="This filed is required")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Invalid email format")]
        [DataType(DataType.EmailAddress)]
        
        public string Email { get; set; }
        [Required(ErrorMessage = "This filed is requied")]
        [DataType(DataType.Password)]
        [RegularExpression("([a-z]|[A-Z]|[0-9]|[\\W]){4}[a-zA-Z0-9\\W]{3,11}", ErrorMessage = "Invalid password format Your Password Should have minimum 7 characters to maximum 15 characters and passowrd should contain minimum 1 upper case alphabet , 1 lower case alphabet, 1 number and 1 special characters ")]
        public string Password { get; set; }
        [Required(ErrorMessage = "This filed is requied")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        [DisplayName("ConfirmPassword")]
        public string ConfirmPassword { get; set; }
        public string FullName { get; set; }
        [Required]
        public string Address { get; set; }
        public bool IsAdmin { get; set; }
    }
}
